app:
  host: 127.0.0.1
  port: 8000
  # API will auto-reload when changes on code files are detected
  reload: true
images:
  image_thumbnail_size: [50, 50]
  waveform_thumbnail_size: [100, 100]
  default_colour_map: viridis
  colourbar_height_pixels: 16
logging:
  log_level: DEBUG
  log_location: /home/runner/work/operationsgateway-api/operationsgateway-api/logs.log
  # Enables/disables information about the origin of the log message
  log_message_location: true
mongodb:
  mongodb_url: mongodb://localhost:27017
  database_name: opsgateway
  # Maximum number of documents to return when querying, similar to ICAT's maxEntities
  max_documents: 1000
  image_store_directory: /home/runner/og-images
auth:
  private_key_path: /home/runner/work/operationsgateway-api/id_rsa
  public_key_path: /home/runner/work/operationsgateway-api/id_rsa.pub
  jwt_algorithm: RS256
  access_token_validity_mins: 60
  refresh_token_validity_days: 7
  fedid_server_url: ldap://fed.cclrc.ac.uk:389
  fedid_server_ldap_realm: FED.CCLRC.AC.UK
experiments:
  user_office_wsdl_url: https://devapi.facilities.rl.ac.uk/ws/UserOfficeWebService?wsdl
  scheduler_wsdl_url: https://devapis.facilities.rl.ac.uk/ws/ScheduleWebService?wsdl
  username: username
  password: password
  first_scheduler_contact_start_date: 2019-01-02T00:00:00Z
  # Cron job string format. Every Monday at 9:00am - 0 9 * * 1
  scheduler_background_frequency: 0 9 * * 1
  scheduler_background_timezone: Europe/London
  scheduler_background_retry_mins: 20
  instrument_name: Gemini
