script_options:
  wipe_database: false
  delete_images: false
  launch_api: true
  ssh_connection_url: 127.0.0.1
database:
  hostname: localhost
  port: 27017
  name: opsgateway
  remote_experiments_file_path: /tmp/experiments_for_mongoimport.json
echo:
  endpoint_url: https://s3.echo.stfc.ac.uk
  access_key: access_key
  secret_key: secret_key
  simulated_data_bucket: og-ci-simulated-data
  # TODO - this needs changing to the bucket created in the job
  images_bucket: og-matt-images-test
  page_size: 12
api:
  host: 127.0.0.1
  port: 8000
  username: backend
  password: back
  log_config_path: /home/runner/work/operationsgateway-api/operationsgateway-api/operationsgateway_api/logging.ini
  gunicorn_num_workers: 8
  timeout_seconds: 500
