services:
  
  # Targets:
  #- add_test_data: Starts the api and ingest some data into the mongodb and minio s3
  #- test: Run the tests against the test data added in previous step
  #- production: Only install the necessary components to run the api
  operations_gateway_api:
    build:
      context: .
      target: add_test_data
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/docs" ]
      interval: 90s       # Check every 30 seconds
      timeout: 1s         # Wait 10 seconds for a response
      retries: 5          # Retry up to 5 times before marking as unhealthy
      start_period: 5s   # Wait 30 seconds before starting health checks

  # Can use this in a shell to look around: docker exec -it mongodb_container mongosh
  mongo:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db  # Mount volume for MongoDB data
      - ./util/realistic_data/init_mongo.js:/docker-entrypoint-initdb.d/mongo-init.js  # Add the init script that adds users
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Available at http://localhost:9001
  minio:
    image: docker.io/bitnami/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: og-test
    ports:
      - "9000:9000"
      - "9001:9001"

# Persist data so test data can used
volumes:
  mongo-data:
    driver: local