services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    ports:
      - "8081:8080"
    volumes:
      - ./testrealm.json:/opt/keycloak/data/import/testrealm.json


#call with
#curl -X POST http://localhost:8081/realms/testrealm/protocol/openid-connect/token
#    -H "Content-Type: application/x-www-form-urlencoded"
#    -d "grant_type=password"
#    -d "client_id=operations-gateway"
#    -d "scope=openid profile email"
#    -d "username=alice"
#    -d "password=password"

#and use id token