name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-24.04
    name: Setup Environment
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install system dependencies for python-ldap
        run: |
          sudo apt-get update
          sudo apt-get install -y libsasl2-dev libldap2-dev libssl-dev

      - name: Install Poetry
        run: pip install poetry

      - name: Ensure Poetry Uses Python 3.11
        run: poetry env use $(which python3.11)

      - name: Load Poetry Cache
        id: poetry-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-3.11-${{ hashFiles('poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-3.11-

      - name: Install Dependencies
        run: poetry install --without simulated-data --no-interaction

  tests:
    runs-on: ubuntu-24.04
    needs: setup
    name: Run Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Poetry Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-3.11-${{ hashFiles('poetry.lock') }}

      - name: Run Tests
        run: poetry run pytest --maxfail=1 --disable-warnings -q

  lint:
    runs-on: ubuntu-24.04
    needs: setup
    name: Linting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Poetry Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-3.11-${{ hashFiles('poetry.lock') }}

      - name: Run Linting
        run: poetry run nox -s lint
